/* Auto-generated by AuthSystem - 2026-06-28T07:38:05.525Z */
// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: 'app_3d7506c5-bff',
  apiKey: 'ak_development_7bc60786a2c4503eac07df461c93f79e'
};
